config/routes.rb
Panda42::Application.routes.draw do
  resources :questions do
  resources :comments
end
  devise_for :users do
    get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  resources :users, :only => :show
  match 'account' => 'users#show'
  match 'user' => 'users#index'
  match 'home' => 'homes#index'
  match 'contact' => 'contacts#index'
  root :to => 'questions#index'
  match 'mostRecent' => 'questions#mostRecent'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :presence => true,
                      :length => { :minimum => 5 }
  belongs_to :question
  belongs_to :user
  attr_accessible :body, :commenter, :user_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :tiltle, :presence => true,
                     :length => { :minimum => 5 }
  validates :content, :presence => true,
                      :length => { :minimum => 10 }
  attr_accessible :content, :tiltle, :user_id
has_many :comments, :dependent => :destroy
belongs_to :user

        def self.text_search(query)
                  if query.present?
                    where('tiltle like :q or content like :q',q: "%#{query}%")
          	else
    		scoped
  		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model

  # attr_accessible :title, :body

  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  validates :name,  :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true
  has_many :questions, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  @question = Question.find(params[:question_id])
    params[:comment][:user_id] = current_user.id
  @comment = @question.comments.create(params[:comment])
  respond_to do |format|
 if @comment.save
    format.html { redirect_to question_path(@question), notice: 'Komentarz utworzony' }
  else
    format.html { redirect_to question_path(@question), notice: 'Komentarz  nie utworzony: Za malo znakow' }
      end
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    @comment = @question.comments.find(params[:id])
    @comment.destroy
    redirect_to question_path(@question)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # GET /questions
  # GET /questions.json
  def index
   @questions  = Question.order('created_at DESC').text_search(params[:query]).page(params[:page]).per_page(5)
   
        
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  #@comments = @question.comments.order('created_at DESC').page(params[:page]).per_page(5)
 @questions  = Question.order('created_at DESC').text_search(params[:query]).page(params[:page]).per_page(5)
    @question = Question.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    
    #@question = current_user.questions.build(params[:question])
    @question = Question.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
  
    #@post = current_user.posts.build(params[:post])
    @question = current_user.questions.new(params[:question])
    #@question = Question.new(params[:question])
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Pytanie utworzone z powodzeniem' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new"  }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    
    @question = Question.find(params[:id])
    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    
    @question = Question.find(params[:id])
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  def show
    @user = User.find(session["warden.user.user.key"][1][0])
  end
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def getRecentQuestions
    return Question.order('created_at DESC').first(5)
  end

  def getMostQuestions
    #return Question.comments.count
    return Question.all(:joins => :comments, :group => 'id', :order => 'count(*) DESC')
  end

  def getUsersByMostComments
    #return Question.comments.count
    return User.all(:joins => :comments, :group => 'id', :order => 'count(*) DESC')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/application/_mostQuestions.html.erb
<% questions.each do |question| %>
<li><%= link_to truncate(question.tiltle, :length => 30, :omission => '...'), question %></li>
<% end %>

app/views/application/_mostUsers.html.erb
<% users.each do |user| %>
<li><%= user.name %> : <%= user.comments.count %> punktów</li>
<% end %>

app/views/application/_recentQuestions.html.erb
<% questions.each do |question| %>
<li><%= link_to truncate(question.tiltle, :length => 30, :omission => '...'), question %></li>
<% end %>

app/views/contacts/index.html.erb
<header>
  <h2>Kontakt</h2>
</header>
<div id="contact">
    <p>email: lplebanski@gmail.com</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Projekt na zaliczenie</title>
    <%= stylesheet_link_tag    "reset", :media => "all" %>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    

</head>
<body>
    <section id="informations">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    </section>
    <nav id="menu">
        <ul class="left">
            <li><%= link_to 'Strona Główna', root_path %></li>
            <li><a href="#"><%= link_to 'Kontakt', '/contact' %></a></li>
        </ul>
        <ul class="right">
            <% if user_signed_in? %>
                <%= link_to 'Utworz Pytanie  ', new_question_path %>
                <%= link_to('Moje Konto  ', '/account') %>
                <%= link_to('Users  ', '/user') %>
                <%= link_to('Wyloguj', destroy_user_session_path, :method => 'delete') %>
            <% else %>
                <%= link_to('Zaloguj', new_user_session_path)  %>
                <%= link_to('Rejestracja', new_user_registration_path)  %>
            <% end %>
        </ul>
    </nav>
    <header>
        <div class="search">
            <%= form_tag questions_path, method: :get, id: "questions_search", class: "form-inline" do %>
            <%= text_field_tag :query, params[:query] %>
            <%= submit_tag "Szukaj", name: nil, class: "btn" %>
            <% end %>
        </div>
    </header>
    <section id="content">
        <%= yield %>
    </section>
</body>
</html>

app/views/questions/_addcomm.html.erb
<% if user_signed_in? %>
<header>
  <h2>Odpowiedz na pytanie</h2>
</header>

<div>
<%= form_for([@question, @question.comments.build]) do |f| %>
  <div class="field">
    <%= f.text_area :body, placeholder: "Napisz odpowiedz" %>
  </div>
  <div class="actions">
<%= f.submit "Utworz post", class: "btn-custom" %>
  </div>
<% end %>
</div>

<% end %>

app/views/questions/_comment.html.erb
<%= will_paginate @question.comments.page(params[:page]).per_page(5) %>
<% @question.comments.order('created_at DESC').page(params[:page]).per_page(5).each do |comment| %>
<div class="question">
  <div class="user">
  
    <img src="/assets/user-icon.jpg">
    <p><%= comment.user.name %></p>
  </div>
  <div class="content">
    <div><%= comment.body %></div>    
    <div class="date"><%= comment.created_at.strftime("%d %B %Y o %H:%M") %> </div>
 </div>
</div>
<% end %>
<%= will_paginate @question.comments.page(params[:page]).per_page(5) %>

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
Tytul pytania<br><%= f.text_area :tiltle, :size => "40x1" %><br>
<%= f.text_area :content, placeholder: "Tresc pytania ...." %><br>

  </div>

  <div class="form-actions">
    <%= f.submit "Utworz pytanie", class: "btn-custom" %>
  </div>
<% end %>

app/views/questions/_trescpyt.html.erb
<div class="question">
  <div class="user">
    <img src="/assets/user-icon.jpg">
    <p><%= @question.user.name %></p>
  </div>
  <div class="content">
    <div><h2><%= @question.tiltle %></h2></div>
    <br/>
    <div><%= @question.content %></div>
    <div class="comments">Liczba odpowiedzi : <%= @question.comments.count %></div>
    <div class="date"><%= @question.created_at.strftime("%d %B %Y o %H:%M") %></div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<head><meta http-equiv="refresh" content="10" /></head>
<header>
  <h2>Pytania</h2>
</header>

<%= will_paginate @questions %>

<% @questions.each do |question| %>
    <div class="question">
      <div class="user">
        <img src="/assets/user-icon.jpg">
        <p><%= question.user.name %></p>
      </div>
      <div class="content">
        <div><a href="#"><h2><%= link_to truncate(question.tiltle, :length => 60, :omission => '...'), question %></h2></a></div>
        <div class="comments">Liczba odpowiedzi : <%= question.comments.count %></div>
        <div class="date"><%= question.created_at.strftime("%d %B %Y at %H:%M") %></div>
      </div>
    </div>
<% end %>

<%= will_paginate @questions %>

app/views/questions/new.html.erb
<header>
  <h2>Zadaj pytanie</h2>
</header>
<div id="create-question">
    <%= render 'form' %>
</div>

app/views/questions/show.html.erb
<header>
  <h2>Treść pytania</h2>
</header>

<%= render 'trescpyt' %>

<header>
  <h2>Odpowiedzi</h2>
</header>

<%= render 'comment' %>

<%= render 'addcomm' %>

app/views/users/index.html.erb
<header><h2>Lista uzytkownikow</h2></header>

<table id="questions" class="display">
    <thead>
        <tr>
            <th>Nazwa użytkownika: </th>
            <th>E-mail:</th>
            <th>Ilość zadanych pytań : </th>
            <th> Ilość udzielonych odpowiedzi: </th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.questions.count %></td>
            <td><%= user.comments.count %></td>
        </tr>
         <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<header><h2>Moje Konto</h2></header>
<div id="myaccount">
    <table>
        <tbody>
            <tr>
                <td><b><%= link_to('Edytuj konto', edit_user_registration_path) %></b></td></td>
                <td rowspan="5"><img src="assets/my-account.png"></td>
                <td class="bg-highlight">Nazwa użytkownika :</td>
                <td class="bg-highlight"><%= @user.name %></td>
            </tr>
            <tr>
                <td></td></td>
                <td class="bg-highlight">E-mail :</td>
                <td class="bg-highlight"><%= @user.email %></td>
            </tr>
            <tr>
                <td></td></td>
                <td class="bg-highlight">Ilość zadanych pytań :</td>
                <td class="bg-highlight"><%= @user.questions.count %></td>
            </tr>
            <tr>
                <td></td>
                <td class="bg-highlight">Ilość wystawionych komentarzy :</td>
                <td class="bg-highlight"><%= @user.comments.count %></td>
            </tr>
            <tr></tr>
        </tbody>
    </table>
</div>